### PR TITLE
Fix database initalization and remove unneeded code

### PR DESCRIPTION
**Pull request by the-blank-x**

### CODE REVIEW

**Comment by Dank-del** [comment]
@the-blank-x My neko uwu

**Comment by the-blank-x** [comment]
> @the-blank-x My neko uwu
owo

**Comment by DragSama** [comment]
O

**Comment by DragSama** [comment]
I didn't even check kek

**Comment by Dank-del** [comment]
@DragSama

**Comment by DragSama** [comment]
> @DragSama
ic

**Comment by Dank-del** [comment]
@DragSama GitHub bot is bad.

**Comment by the-blank-x** [comment]
> I didn't even check kek

@MeliodasBot messaged me lmao

**Comment by DragSama** [comment]
> > I didn't even check kek
> 
> @MeliodasBot messaged me lmao

O, Tho I think his issue was because of +srv being in connection string

**Comment by DragSama** [comment]
> @DragSama GitHub bot is bad.

Sedlyf

**Comment by the-blank-x** [comment]
> > > I didn't even check kek
> > 
> > 
> > @MeliodasBot messaged me lmao
> 
> O, Tho I think his issue was because of +srv being in connection string

He had issues with the database not having some _id = 1 or something. I did some research and the init code wasn't even called.

**Comment by DragSama** [comment]
> > > > I didn't even check kek
> > > 
> > > 
> > > @MeliodasBot messaged me lmao
> > 
> > 
> > O, Tho I think his issue was because of +srv being in connection string
> 
> He had issues with the database not having some _id = 1 or something. I did some research and the init code wasn't even called.

Ah, I never encountered that because collections were already made

**Comment by DragSama** [comment]
> > > > I didn't even check kek
> > > 
> > > 
> > > @MeliodasBot messaged me lmao
> > 
> > 
> > O, Tho I think his issue was because of +srv being in connection string
> 
> nah that was not the cause

👍

**Comment by Dank-del** [comment]
@DragSama Cringe emoji

**Comment by DragSama** [comment]
> @DragSama Cringe emoji

💎

**Pull request merged**
